apiVersion: v1
kind: Service
metadata:
  name: code_pulse_service
spec:
  selector:
    app: code_pulse
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8080  
  type: LoadBalancer  
---
